AWSTemplateFormatVersion: '2010-09-09'

Description: Base resources for the Lists service

Parameters:
  pBuild:
    Type: String
    Description: The build number
  pCleanBranch:
    Type: String
    Description: The clean branch, can be used in resource names
  pEnvironment:
    Type: String
    Description: The AWS environment this belongs to
  pProductName:
    Type: String
    Description: The product name, used in resource names
  pCognitoStackName:
    Type: String
    Description: The name of the Cognito stack
  pAppClientHost:
    Type: String
    Description: The host for the app client for the frontend
  pAppClientServiceHost:
    Type: String
    Description: The host for the app client for the service
  pOidcConnectProvider:
    Type: String
    Description: The OIDC connect provider
  pClusterOidcIssuerUrl:
    Type: String
    Description: The OIDC issuer URL for the cluster
  pEksNamespace:
    Type: String
    Description: The EKS namespace for the service account

Conditions:

  IsDev: !Equals
    - !Ref pEnvironment
    - development
  NotProd: !Not
    - !Equals
      - !Ref pEnvironment
      - production
  IsFirstBuild: !Equals [!Ref pBuild, "1"]

Resources:

  DocDbPasswordSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 
              - lists-${ResourceName}
              - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
      Description: !Sub Lists app ${pEnvironment} secrets
      GenerateSecretString:
        SecretStringTemplate: |
          {
            "db-password": "",
            "cas-client-secret": "",
            "cas-s2s-client-secret": ""
          }
        GenerateStringKey: db-password
        PasswordLength: 12
        ExcludeCharacters: "/@\"\\#<> "
      Tags:
        - Key: Name
          Value: !Sub
            - ${pProductName}-${ResourceName}
            - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]

  ListsAppClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      AccessTokenValidity: 8
      AllowedOAuthFlows: 
        - code
      AllowedOAuthFlowsUserPoolClient: True
      AllowedOAuthScopes: 
        - ala/attrs
        - ala/internal
        - ala/roles
        - email
        - openid
        - profile
        - users/read
      AuthSessionValidity: 3
      CallbackURLs: 
        - !Sub ${pAppClientHost}
        - !Sub ${pAppClientHost}/
        - !Sub ${pAppClientHost}/callback?client_name=OidcClient
        - !Sub ${pAppClientHost}/oauth2-redirect.html
      ClientName: !Sub
          - species-lists-ui-${ResourceName}
          - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
      DefaultRedirectURI: !Sub ${pAppClientHost}
      EnablePropagateAdditionalUserContextData: False
      EnableTokenRevocation: True
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_CUSTOM_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      GenerateSecret: False
      IdTokenValidity: 8
      LogoutURLs: 
        - !Sub ${pAppClientHost}
        - !Sub ${pAppClientHost}/
      PreventUserExistenceErrors: ENABLED
      RefreshTokenValidity: 30
      SupportedIdentityProviders:
        - COGNITO
        - Facebook
        - Google
        - AAF
        - SignInWithApple
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      UserPoolId: 
        Fn::ImportValue:
            !Sub ${pCognitoStackName}-UserPoolId

  ListsServiceAppClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      AccessTokenValidity: 8
      AllowedOAuthFlows: 
        - client_credentials
      AllowedOAuthFlowsUserPoolClient: True
      AllowedOAuthScopes: 
        - ala/attrs
        - ala/roles
        - ala/internal
        - users/read
      AuthSessionValidity: 3
      CallbackURLs: 
        - !Sub ${pAppClientServiceHost}
        - !Sub ${pAppClientServiceHost}/
        - !Sub ${pAppClientServiceHost}/callback?client_name=OidcClient
        - !Sub ${pAppClientServiceHost}/oauth2-redirect.html
      ClientName: !Sub
          - species-lists-s2s-${ResourceName}
          - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
      DefaultRedirectURI: !Sub ${pAppClientServiceHost}/callback?client_name=OidcClient
      EnablePropagateAdditionalUserContextData: True
      EnableTokenRevocation: True
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_CUSTOM_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      GenerateSecret: True
      IdTokenValidity: 8
      LogoutURLs: 
        - !Sub ${pAppClientServiceHost}
        - !Sub ${pAppClientServiceHost}/
      PreventUserExistenceErrors: ENABLED
      RefreshTokenValidity: 30
      SupportedIdentityProviders:
        - COGNITO
        - Facebook
        - Google
        - AAF
        - SignInWithApple
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      UserPoolId: 
        Fn::ImportValue:
            !Sub ${pCognitoStackName}-UserPoolId

  LoadBalancerAccessLogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub
        - ala-${pProductName}-${ResourceName}-alb-access-logs
        - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: "ExpireOldLogs"
            Status: Enabled
            ExpirationInDays: 90
            Prefix: "logs/"
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      Tags:
        - Key: Name
          Value: LoadBalancerAccessLogs

  LoadBalancerAccessLogsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LoadBalancerAccessLogsBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowELBAccess
            Effect: Allow
            Principal:
              Service: "logdelivery.elasticloadbalancing.amazonaws.com"
            Action: "s3:PutObject"
            Resource: !Sub "arn:aws:s3:::${LoadBalancerAccessLogsBucket}/logs/AWSLogs/${AWS::AccountId}/*"

  ListsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Effect": "Allow",
                  "Principal": {
                      "Federated": "${pOidcConnectProvider}"
                  },
                  "Action": "sts:AssumeRoleWithWebIdentity",
                  "Condition": {
                      "StringEquals": {
                                        "${pClusterOidcIssuerUrl}:sub": "system:serviceaccount:${pEksNamespace}:lists-service-account-${pCleanBranch}",
                                        "${pClusterOidcIssuerUrl}:aud": "sts.amazonaws.com"
                      }
                  }
              },
              {
                "Effect": "Allow",
                "Principal": {
                  "Service":  "ec2.amazonaws.com"
        
                },
                "Action": "sts:AssumeRole"
              }
          ]
        }
      Description: !Sub 'IAM role for lists uploads bucket access ${AWS::StackName} ${pEnvironment} build ${pBuild}'
      ManagedPolicyArns:
        - !Sub arn:aws:iam::${AWS::AccountId}:policy/cpt/cptSSMInstanceCoreCloudWatchPatch
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:DeleteObject
                  - s3:DeleteObjectVersion
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:PutObject
                Resource:
                  - !Sub arn:aws:s3:::${ListsUploadsBucket}
                  - !Sub arn:aws:s3:::${ListsUploadsBucket}/*
          PolicyName: lists-uploads-bucket
      RoleName: !Sub
        - ${pProductName}-${ResourceName}
        - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
      Tags:
        - Key: Name
          Value: !Sub
            - ${pProductName}-${ResourceName}
            - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]

  ListsInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub
        - ${pProductName}-${ResourceName}
        - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
      Roles:
        - !Ref ListsRole

  ListsUploadsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub
        - ala-${pProductName}-${ResourceName}
        - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
      LifecycleConfiguration:
        Rules:
          - Id: delete
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
            Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        IgnorePublicAcls: TRUE
        RestrictPublicBuckets: TRUE
      Tags:
        - Key: Name
          Value: !Sub
            - ${pProductName}-${ResourceName}
            - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]

Outputs:

  AppClientId:
    Description: The app client for the lists frontend
    Value: !Ref ListsAppClient
    Export:
      Name: !Sub ${AWS::StackName}-AppClientId

  DocDbPasswordSecretName:
    Description: The Secrets name for lists 
    Value: !Sub
      - lists-${ResourceName}
      - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
    Export:
      Name: !Sub ${AWS::StackName}-DocDbPasswordSecretName

  ServiceAppClientId:
    Description: The app client for the lists backend service
    Value: !Ref ListsServiceAppClient
    Export:
      Name: !Sub ${AWS::StackName}-ServiceAppClientId

  LoadBalancerAccessLogsBucket:
    Description: The S3 bucket for the Load Balancer access logs
    Value: !Ref LoadBalancerAccessLogsBucket

  ListsUploadsBucket:
    Description: The S3 bucket for the Lists uploads service
    Value: !Ref ListsUploadsBucket

  ListsRoleArn:
    Description: The role ARN for the Lists service
    Value: !GetAtt ListsRole.Arn
