AWSTemplateFormatVersion: '2010-09-09'

Description: Base resources for the Lists service

Parameters:
  pBuild:
    Type: String
    Description: The build number
  pCleanBranch:
    Type: String
    Description: The clean branch, can be used in resource names
  pEnvironment:
    Type: String
    Description: The AWS environment this belongs to
  pProductName:
    Type: String
    Description: The product name, used in resource names
  pCognitoStackName:
    Type: String
    Description: The name of the Cognito stack
  pAppClientHost:
    Type: String
    Description: The host for the app client for the frontend
  pAppClientServiceHost:
    Type: String
    Description: The host for the app client for the service

Conditions:

  IsDev: !Equals
    - !Ref pEnvironment
    - development
  NotProd: !Not
    - !Equals
      - !Ref pEnvironment
      - production
  IsFirstBuild: !Equals [!Ref pBuild, "1"]

Resources:

  DocDbPasswordSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 
              - lists-${ResourceName}
              - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
      Description: !Sub Lists app ${pEnvironment} secrets
      GenerateSecretString:
        SecretStringTemplate: |
          {
            "db-password": "",
            "cas-client-secret": "",
            "cas-s2s-client-secret": ""
          }
        GenerateStringKey: db-password
        PasswordLength: 12
        ExcludeCharacters: "/@\" "
      Tags:
        - Key: Name
          Value: !Sub
            - ${pProductName}-${ResourceName}
            - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]

  ListsAppClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      AccessTokenValidity: 8
      AllowedOAuthFlows: 
        - code
      AllowedOAuthFlowsUserPoolClient: True
      AllowedOAuthScopes: 
        - ala/attrs
        - ala/internal
        - ala/roles
        - email
        - openid
        - profile
        - users/read
      AuthSessionValidity: 3
      CallbackURLs: 
        - !Sub ${pAppClientHost}
        - !Sub ${pAppClientHost}/
        - !Sub ${pAppClientHost}/callback?client_name=OidcClient
        - !Sub ${pAppClientHost}/oauth2-redirect.html
      ClientName: !Sub
          - species-lists-ui-${ResourceName}
          - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
      DefaultRedirectURI: !Sub ${pAppClientHost}
      EnablePropagateAdditionalUserContextData: False
      EnableTokenRevocation: True
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_CUSTOM_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      GenerateSecret: False
      IdTokenValidity: 8
      LogoutURLs: 
        - !Sub ${pAppClientHost}
        - !Sub ${pAppClientHost}/
      PreventUserExistenceErrors: ENABLED
      RefreshTokenValidity: 30
      SupportedIdentityProviders:
        - COGNITO
        - Facebook
        - Google
        - AAF
        - SignInWithApple
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      UserPoolId: 
        Fn::ImportValue:
            !Sub ${pCognitoStackName}-UserPoolId

  ListsServiceAppClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      AccessTokenValidity: 8
      AllowedOAuthFlows: 
        - client_credentials
      AllowedOAuthFlowsUserPoolClient: True
      AllowedOAuthScopes: 
        - ala/attrs
        - ala/roles
        - ala/internal
        - users/read
      AuthSessionValidity: 3
      CallbackURLs: 
        - !Sub ${pAppClientServiceHost}
        - !Sub ${pAppClientServiceHost}/
        - !Sub ${pAppClientServiceHost}/callback?client_name=OidcClient
        - !Sub ${pAppClientServiceHost}/oauth2-redirect.html
      ClientName: !Sub
          - species-lists-s2s-${ResourceName}
          - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
      DefaultRedirectURI: !Sub ${pAppClientServiceHost}/callback?client_name=OidcClient
      EnablePropagateAdditionalUserContextData: True
      EnableTokenRevocation: True
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_CUSTOM_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      GenerateSecret: True
      IdTokenValidity: 8
      LogoutURLs: 
        - !Sub ${pAppClientServiceHost}
        - !Sub ${pAppClientServiceHost}/
      PreventUserExistenceErrors: ENABLED
      RefreshTokenValidity: 30
      SupportedIdentityProviders:
        - COGNITO
        - Facebook
        - Google
        - AAF
        - SignInWithApple
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      UserPoolId: 
        Fn::ImportValue:
            !Sub ${pCognitoStackName}-UserPoolId

Outputs:

  AppClientId:
    Description: The app client for the lists frontend
    Value: !Ref ListsAppClient
    Export:
      Name: !Sub ${AWS::StackName}-AppClientId

  DocDbPasswordSecretName:
    Description: The Secrets name for lists 
    Value: !Sub
      - lists-${ResourceName}
      - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
    Export:
      Name: !Sub ${AWS::StackName}-DocDbPasswordSecretName

  ServiceAppClientId:
    Description: The app client for the lists backend service
    Value: !Ref ListsServiceAppClient
    Export:
      Name: !Sub ${AWS::StackName}-ServiceAppClientId
