mongodb:username: adminuser
mongodb.password: ".,9H%7C%3DqAArL1"
mongodb.host: development-docdb-cluster.cluster-ch1znchb8ne9.ap-southeast-2.docdb.amazonaws.com
oidc.discoveryUri: https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_OOXU9GW39/.well-known/openid-configuration
oidc.clientId: 3u4obi49r09eu87lcravb1h95b
bie.baseUrl: https://bie-ws.ala.org.au/ws
images.baseUrl: https://images.ala.org.au
namematching.baseUrl: https://namematching-ws.ala.org.au/
userdetails.baseUrl: https://api.test.ala.org.au/userdetails/cognito
