version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    container_name: species-lists-elastic
    environment:
      - node.name=elasticsearch
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - /data/elastic:/usr/share/elasticsearch/data
    restart: on-failure
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://elasticsearch:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
  mongodb:
    image: mongo:6.0
    container_name: species-lists-mongo
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/data/db
  namematching:
    image: atlasoflivingaustralia/ala-namematching-service:v20210811-3
    container_name: species-lists-namematching
    restart: on-failure
    ports:
      - "9179:9179"
#  lists:
#    image: atlasoflivingaustralia/lists-service:latest
#    container_name: lists-service
#    volumes:
#      - type: bind
#        source: /data/lists-service/config/lists-service-config.properties
#        target: /data/lists-service/config/lists-service-config.properties
#      - /data/lists/tmp:/tmp
#    restart: on-failure
#    ports:
#      - "8080:8080"
volumes:
  mongodb_data_container:
  elasticsearch-data:
    driver: local