version: 0.2
###
# This build project builds the lists service and pushes the Docker image 
# to Amazon ECR

env:
  shell: bash
  variables:
    JAVA_TOOL_OPTIONS: -Dhttps.protocols=TLSv1.2
  secrets-manager:
    DOCKER_PASSWORD: $ALA_SECRETS_NAME:dockerhub-password
  exported-variables:
    - BUILD_TAG
phases:
  install:
    commands:
      - echo Registering QEMU emulators for cross-platform builds...
      - docker run --rm --privileged public.ecr.aws/eks-distro-build-tooling/binfmt-misc:qemu-v9.2.2 --install all
      - docker buildx version
      - docker buildx create --use --name multiarch-builder

  build:
    commands:
      - echo Build started on $(date)
      - echo Logging in to Amazon ECR...
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - aws ecr get-login-password | docker login -u AWS --password-stdin "https://$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
      - export BUILD_TAG=$CLEAN_BRANCH-$CODEBUILD_BUILD_NUMBER
      - echo build tag is $BUILD_TAG
      - echo "$BUILD_TAG" > build_tag.txt
      - echo Building and pushing the multi-arch Docker image to ECR...
      - |
          docker buildx build --platform linux/amd64,linux/arm64 \
                              -f lists-service/src/main/docker/Dockerfile \
                              -t $ECR_REPO:$BUILD_TAG \
                              -t $ECR_REPO:$IMAGE_TAG \
                              --push \
                              lists-service

  post_build:
    commands:
      - echo Post-build phase...
      - echo Build completed on $(date)
