version: 0.2
###
# This build project sets up the eks context and deploys the lists service
# using Helm

env:
  shell: bash
  variables:
    JAVA_TOOL_OPTIONS: -Dhttps.protocols=TLSv1.2

phases:

  install:
    commands:
      - echo Installing dependencies...
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      - chmod 700 get_helm.sh
      - ./get_helm.sh

  pre_build:
    commands:
      - echo Entered the pre_build phase...

  build:
    commands:
      - echo Build started on $(date)
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
      - cd lists-service/helm
      - echo helm upgrade --install $HELM_RELEASE_NAME  . 
                      -n $EKS_NAMESPACE 
                      --set image.repository=$ECR_REPO 
                      --set image.tag=$BUILD_TAG
                      --set ingress.hostname=$WS_SUB_DOMAIN.$HOSTED_ZONE
                      --set ingress.certificateArn=$APP_CERTIFICATE
                      --set ingress.WafArn=$WAF_ARN
                      -f $CODEBUILD_SRC_DIR_ExportConfigArtifact/helm-values.yaml
                      --set deploymentAnnotations.checksum/configs="$(md5sum $CODEBUILD_SRC_DIR_ExportConfigArtifact/helm-values.yaml | awk '{print $1}')"
                      --set deploymentAnnotations.commitHash=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - helm upgrade --install $HELM_RELEASE_NAME . 
                      -n $EKS_NAMESPACE
                      --set image.repository=$ECR_REPO 
                      --set image.tag=$BUILD_TAG
                      --set ingress.hostname=$WS_SUB_DOMAIN.$HOSTED_ZONE
                      --set ingress.certificateArn=$APP_CERTIFICATE
                      --set ingress.WafArn=$WAF_ARN
                      -f $CODEBUILD_SRC_DIR_ExportConfigArtifact/helm-values.yaml
                      --set deploymentAnnotations.checksum/configs="$(md5sum $CODEBUILD_SRC_DIR_ExportConfigArtifact/helm-values.yaml | awk '{print $1}')"
                      --set deploymentAnnotations.commitHash=$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo Post-build phase...
      - echo Build completed on $(date)
