version: 0.2
###
# This build project sets up the eks context and deploys the lists service
# using Helm

env:
  shell: bash
  variables:
    JAVA_TOOL_OPTIONS: -Dhttps.protocols=TLSv1.2
  secrets-manager:
    MONGODB_PASSWORD: $LISTS_SECRET_NAME:db-password

phases:

  install:
    commands:
      - echo Installing dependencies...
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      - chmod 700 get_helm.sh
      - ./get_helm.sh

  pre_build:
    commands:
      - echo getting app clientID and secret
      - aws cognito-idp describe-user-pool-client --user-pool-id $USER_POOL_ID --client-id $SERVICE_APP_CLIENT_ID --region $AWS_REGION > app_client.json
      - export WEBSERVICE_CLIENT_ID=$(jq -r '.UserPoolClient.ClientId' app_client.json)
      - echo WEBSERVICE_CLIENT_ID=$WEBSERVICE_CLIENT_ID
      - export WEBSERVICE_CLIENT_SECRET=$(jq -r '.UserPoolClient.ClientSecret' app_client.json)
      - echo WEBSERVICE_CLIENT_SECRET=${WEBSERVICE_CLIENT_SECRET:0:3}************

  build:
    commands:
      - echo Build started on $(date)
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
#      - kubectl config set-context --current --namespace=$PRODUCT_NAME
#      - printf "$(kubectl config current-context)\n"
      # do we need to create the service account here?
      - cd lists-service/helm
      - | 
        echo "mongodb:
          host: $MONGODB_HOST
          password: \"$MONGODB_PASSWORD\"
          username: $MONGODB_USERNAME
        oidc:
          discoveryUri: $OIDC_DISCOVERY_URI
          clientId: $OIDC_CLIENT_ID
        webservice:
          clientId: $WEBSERVICE_CLIENT_ID
          clientSecret: $WEBSERVICE_CLIENT_SECRET
        app:
          url: $UI_SUB_DOMAIN.$HOSTED_ZONE
          ws-url: $WS_SUB_DOMAIN.$HOSTED_ZONE
        bie:
          baseUrl: $BIE_BASE_URL
        biocache:
          baseUrl: $BIOCACHE_BASE_URL
        collectory:
          baseUrl: $COLLECTORY_BASE_URL
        images:
          baseUrl: $IMAGES_BASE_URL
        namematching:
          baseUrl: $NAMEMATCHING_BASE_URL
        userdetails:
          baseUrl: $USERDETAILS_BASE_URL" > helm_values.yaml
      - echo helm values
      - cat helm_values.yaml
      - echo helm upgrade --install $HELM_RELEASE_NAME  . 
                      -n lists 
                      --set image.repository=$ECR_REPO 
                      --set image.tag=$CLEAN_BRANCH-$CODEBUILD_BUILD_NUMBER
                      --set ingress.hostname=$WS_SUB_DOMAIN.$HOSTED_ZONE
                      --set ingress.certificateArn=$APP_CERTIFICATE
                      -f helm_values.yaml
      - helm upgrade --install $HELM_RELEASE_NAME . 
                      -n lists
                      --set image.repository=$ECR_REPO 
                      --set image.tag=$CLEAN_BRANCH-$CODEBUILD_BUILD_NUMBER
                      --set ingress.hostname=$WS_SUB_DOMAIN.$HOSTED_ZONE
                      --set ingress.certificateArn=$APP_CERTIFICATE
                      -f helm_values.yaml
  post_build:
    commands:
      - echo Post-build phase...
      - echo Build completed on $(date)
