version: 0.2
###
# This build project sets up the eks context and deploys the lists service
# using Helm

env:
  shell: bash
  variables:
    JAVA_TOOL_OPTIONS: -Dhttps.protocols=TLSv1.2

phases:

  install:
    commands:
      - echo Installing dependencies...
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      - chmod 700 get_helm.sh
      - ./get_helm.sh

  build:
    commands:
      - echo Build started on $(date)
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
      - eksctl delete iamserviceaccount --name=lists-service-account-$CLEAN_BRANCH --namespace=$EKS_NAMESPACE --cluster=$EKS_CLUSTER_NAME
      - cd lists-service/helm
      - echo helm uninstall $HELM_RELEASE_NAME -n $EKS_NAMESPACE
      - |
        if helm list -n $EKS_NAMESPACE | grep -q $HELM_RELEASE_NAME; then
          helm uninstall $HELM_RELEASE_NAME -n $EKS_NAMESPACE
        else
          echo "Release $HELM_RELEASE_NAME does not exist."
        fi

  post_build:
    commands:
      - echo Post-build phase...
      - echo Build completed on $(date)
