version: 0.2
###
# This build project builds the LISTS site files ready for upload to s3

env:
  shell: bash

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: $NODE_VERSION
    commands:
      - cp lists-ui/vite.properties lists-ui/.env
      - echo injecting app client config
      - |
        if [[ "$ENVIRONMENT" == "production" || "$ENVIRONMENT" == "staging" ]]; then
          export VITE_AUTH_CLIENT_ID=$PROD_VITE_AUTH_CLIENT_ID
          export VITE_AUTH_AUTHORITY="https://auth.ala.org.au/cas/oidc/.well-known"
          export VITE_AUTH_REDIRECT_URI=$VITE_AUTH_REDIRECT_URI
          export VITE_AUTH_END_SESSION_URI="https://auth.ala.org.au/cas/logout"
        fi
      - sed -i "s/VITE_AUTH_CLIENT_ID=.*$/VITE_AUTH_CLIENT_ID=$VITE_AUTH_CLIENT_ID/g" lists-ui/config/.env.$ENVIRONMENT
      - cat lists-ui/config/.env.$ENVIRONMENT
      - cd lists-ui
  pre_build:
    commands:
      - echo running npm install...
      - npm install @rollup/rollup-linux-x64-gnu
      - npm ci --platform=linux --arch=x64
  build:
    commands:
      - echo building...
      - npm run build:$ENVIRONMENT

artifacts:
  base-directory: lists-ui/dist
  files:
    - '**/*'
